There are some potential issues when running the validate.py

# --ignore CountryValidator
There is one location with invalid phone # from the json data.
For example, 39496400623.

# --ignore LatLngDuplicationValidator