There are some potential issues when running the validate.py

# 1 location was eliminated cause it is coming soon
