There are some potential issues when running the validate.py

# Then number of POI
It is confirmed that there are 137 stores in citymd.net from the website, but valiator says 113
I tried --ignore StateLevelCountValidator or --ingore CoundValidator, but still 1 checks failing.
